import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Trenote : Login/Signup here</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <button color="primary" variant="contained">
          Click Me
        </button>
      </main>
    </div>
  );
}
